# This is a basic workflow to help you get started with Actions
name: gh-deploy

on:
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build:
    name: Jupyter-book Github Pages automatic deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # python pip install jupyter-book ghp-import
          python -m pip install -r requirements.txt


      # Build the book and Push the book's HTML to github-pages
      - name: build jupyter-book and copy book's HTML to the gh-pages branch
        run: |
          jupyter-book build ./
          ghp-import -n -p -f _build/html


